name: Build LBTC CLI Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PyInstaller
        run: python -m pip install --upgrade pip pyinstaller

      - name: Build EXE
        run: >
          python -m PyInstaller
          --onefile
          --console
          --name lbtc-miner-cli
          lbtc-miner-cli.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: lbtc-miner-cli-windows
          path: dist/lbtc-miner-cli.exe
